In [2]:
#imports
import torch
import pandas as  pd
import numpy as np
import matplotlib.pyplot as plt

### Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor((7,7))
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [14]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX.ndim

2

In [35]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                        [[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [30]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [1, 2, 3]]])

In [31]:
TENSOR.ndim

3

In [32]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5],
        [1, 2, 3]])

In [36]:
TENSOR.size()

torch.Size([2, 3, 3])

### Random Tensors

In [40]:

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.3816, 0.3492, 0.4755, 0.1406],
        [0.6308, 0.3075, 0.0675, 0.5346],
        [0.5405, 0.5573, 0.9363, 0.7519]])

In [43]:
# Create a a random tensor with similar shape ot an image
random_image_tensor = torch.rand(size = (3, 224,224))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [44]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
# Create a tensor fo all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors

In [53]:
# Use torch.range()
one_to_ten = torch.arange(start=0,end=11, step = 2)

In [54]:
# Creating tensors like
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [55]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [56]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

### Tensor datatypes
***Note***: Tensor datatypes is one of the 3 big errors you'll run into
1. Tensors not right datatype
2. tensors not right shape
3. tensors not on the right device

In [57]:
float_32_tensor

tensor([3., 6., 9.])

In [58]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [61]:
new = float_16_tensor *float_32_tensor

In [64]:
new.dtype

torch.float32

In [66]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)

In [67]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand([3,3,3]).type(torch.long)
some_tensor

tensor([[[0.0304, 0.3002, 0.7150],
         [0.7719, 0.6552, 0.4513],
         [0.2302, 0.8468, 0.8650]],

        [[0.6733, 0.7107, 0.9972],
         [0.0511, 0.8684, 0.8742],
         [0.7498, 0.8447, 0.6262]],

        [[0.1218, 0.8315, 0.7360],
         [0.9799, 0.7194, 0.7285],
         [0.1702, 0.4247, 0.0036]]])

In [75]:
print(f"Datattype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f'Device tensor is on: {some_tensor.device}')

Datattype of tensor: torch.int64
Shape of tensor: torch.Size([3, 3, 3])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

In [77]:
# Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [78]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [79]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [81]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication
1. Element wise multiplication
2. Matrix Multiplication (dot product)

In [83]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [84]:
torch.matmul(tensor,tensor)

tensor(14)

In [85]:
# Matrix multiplcation by hand
1*1 + 2*2 + 3*3

14

In [86]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.15 ms, sys: 4.25 ms, total: 8.4 ms
Wall time: 6.49 ms


In [87]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 2.57 ms, sys: 0 ns, total: 2.57 ms
Wall time: 1.36 ms


tensor(14)

### One of the common errors

Shape errors

Two rules for matrix multiplication
1. The 2 inner dimensions need to match:
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [92]:
# To fix the tensor shape issues, we can manipulate the shape using transpose
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [93]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [95]:
# Find the min
torch.min(x), x.max()

(tensor(0), tensor(90))

In [99]:
# Find the mean: not long doesn't work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [100]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [103]:
min_value, min_index = torch.min(x, dim=0)

In [104]:
min_index

tensor(0)

In [105]:
x.argmin()

tensor(0)

In [106]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keeps the same memory
* stacking - combine multiple tensors on top of each other
* Squeeze - removes all `1` dimensions from a tensor
* Unsequeeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [107]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [111]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [112]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [113]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [122]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [133]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [136]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [137]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [141]:
# Torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"\nPrevious target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [142]:
# torch.permute - rearranges the dimensions of a target tensor
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color)_channels]


In [145]:
#Permute the original tensor to rearrange the axis
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0 -1, 1_2, 2->0
print(x_permuted.shape)
print(x_original.shape)

torch.Size([3, 224, 224])
torch.Size([224, 224, 3])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [146]:
x = torch.arange(1,10).reshape(1,3,3)

In [148]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [149]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [151]:
x[0][2][2]

tensor(9)

In [153]:
x[:,:,1]

tensor([[2, 5, 8]])

In [156]:
x[0,1,1]

tensor(5)

In [158]:
x[0,:,2]

tensor([3, 6, 9])

In [162]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch takes numpy's dtype
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [163]:
# Change the value of array, what will this do to 'tensor'
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [164]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [165]:
numpy_tensor.dtype

dtype('float32')

In [166]:
# Change the tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -. update random number to try and make them better representations of the data -> again -> again -> again -> again...

In [167]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7147, 0.3732, 0.0817, 0.9902],
        [0.1799, 0.3408, 0.7321, 0.3241],
        [0.9682, 0.1182, 0.0754, 0.2561]])
tensor([[0.6871, 0.5257, 0.2279, 0.3727],
        [0.4744, 0.3812, 0.2683, 0.0328],
        [0.9287, 0.7471, 0.9582, 0.4196]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [169]:
# Let's make some random but reporducible tensors

#set the random seed
RANDOM_SEED = 49
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0469, 0.2767, 0.2478, 0.9267],
        [0.1418, 0.7192, 0.2505, 0.2332],
        [0.9189, 0.6753, 0.1225, 0.2415]])
tensor([[0.0469, 0.2767, 0.2478, 0.9267],
        [0.1418, 0.7192, 0.2505, 0.2332],
        [0.9189, 0.6753, 0.1225, 0.2415]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Exercises